name: test

on:
  pull_request_review:
    types: [submitted]
    branches: ['master']

jobs:
  test-usage:
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.review.commit_id }}

      - name: Notarize and verify PR
        uses: docker://codenotary/notarize-and-verify-pr:latest
        with:
          # Args are (in this order):
          # - LC REST API URL
          # - LC REST API personal token
          # - LC gRPC host
          # - LC gRPC port
          # - LC ledger ID
          # - comma-separated list of required PR approvers (GitHub usernames)
          # - GitHub username (signer ID) of the current PR approver
          # NOTE: to get the args from secrets use the following syntax:
          #       ${{ secrets.SOME_SECRET_NAME }}
          args: >
            http://<CNIL-REST-API-host>:8000/api/v1
            Dal8SLBVMFq3363s5h4AgFrN6U5tjoNC4vmSoPoPIZlWy1M2-nci-MuRLoueCNlh
            <CNIL-gRPC-API-host>
            3324
            42139843608656000
            padurean,padurean-alt
            ${{ github.event.review.user.login }}
